[Block1_1]
Measure = Calc
Formula = [MeasureBand0]>0.0
DynamicVariables = 1
IfCondition = ([Block1_1]=1)
IfTrueAction = [!SetVariable Block1_1Color #Color#]
IfFalseAction = [!SetVariable Block1_1Color 0,0,0,0]

[Block1_2]
Measure = Calc
Formula = [MeasureBand0]>0.1
DynamicVariables = 1
IfCondition = ([Block1_2]=1)
IfTrueAction = [!SetVariable Block1_2Color #Color#]
IfFalseAction = [!SetVariable Block1_2Color 0,0,0,0]

[Block1_3]
Measure = Calc
Formula = [MeasureBand0]>0.2
DynamicVariables = 1
IfCondition = ([Block1_3]=1)
IfTrueAction = [!SetVariable Block1_3Color #Color#]
IfFalseAction = [!SetVariable Block1_3Color 0,0,0,0]

[Block1_4]
Measure = Calc
Formula = [MeasureBand0]>0.3
DynamicVariables = 1
IfCondition = ([Block1_4]=1)
IfTrueAction = [!SetVariable Block1_4Color #Color#]
IfFalseAction = [!SetVariable Block1_4Color 0,0,0,0]

[Block1_5]
Measure = Calc
Formula = [MeasureBand0]>0.4
DynamicVariables = 1
IfCondition = ([Block1_5]=1)
IfTrueAction = [!SetVariable Block1_5Color #Color#]
IfFalseAction = [!SetVariable Block1_5Color 0,0,0,0]

[Block1_6]
Measure = Calc
Formula = [MeasureBand0]>0.5
DynamicVariables = 1
IfCondition = ([Block1_6]=1)
IfTrueAction = [!SetVariable Block1_6Color #Color#]
IfFalseAction = [!SetVariable Block1_6Color 0,0,0,0]

[Block1_7]
Measure = Calc
Formula = [MeasureBand0]>0.6
DynamicVariables = 1
IfCondition = ([Block1_7]=1)
IfTrueAction = [!SetVariable Block1_7Color #Color#]
IfFalseAction = [!SetVariable Block1_7Color 0,0,0,0]

[Block1_8]
Measure = Calc
Formula = [MeasureBand0]>0.7
DynamicVariables = 1
IfCondition = ([Block1_8]=1)
IfTrueAction = [!SetVariable Block1_8Color #Color#]
IfFalseAction = [!SetVariable Block1_8Color 0,0,0,0]

[Block1_9]
Measure = Calc
Formula = [MeasureBand0]>0.8
DynamicVariables = 1
IfCondition = ([Block1_9]=1)
IfTrueAction = [!SetVariable Block1_9Color #Color#]
IfFalseAction = [!SetVariable Block1_9Color 0,0,0,0]

[Block1_10]
Measure = Calc
Formula = [MeasureBand0]>0.9
DynamicVariables = 1
IfCondition = ([Block1_10]=1)
IfTrueAction = [!SetVariable Block1_10Color #Color#]
IfFalseAction = [!SetVariable Block1_10Color 0,0,0,0]

[Block2_1]
Measure = Calc
Formula = [MeasureBand1]>0.0
DynamicVariables = 1
IfCondition = ([Block2_1]=1)
IfTrueAction = [!SetVariable Block2_1Color #Color#]
IfFalseAction = [!SetVariable Block2_1Color 0,0,0,0]

[Block2_2]
Measure = Calc
Formula = [MeasureBand1]>0.1
DynamicVariables = 1
IfCondition = ([Block2_2]=1)
IfTrueAction = [!SetVariable Block2_2Color #Color#]
IfFalseAction = [!SetVariable Block2_2Color 0,0,0,0]

[Block2_3]
Measure = Calc
Formula = [MeasureBand1]>0.2
DynamicVariables = 1
IfCondition = ([Block2_3]=1)
IfTrueAction = [!SetVariable Block2_3Color #Color#]
IfFalseAction = [!SetVariable Block2_3Color 0,0,0,0]

[Block2_4]
Measure = Calc
Formula = [MeasureBand1]>0.3
DynamicVariables = 1
IfCondition = ([Block2_4]=1)
IfTrueAction = [!SetVariable Block2_4Color #Color#]
IfFalseAction = [!SetVariable Block2_4Color 0,0,0,0]

[Block2_5]
Measure = Calc
Formula = [MeasureBand1]>0.4
DynamicVariables = 1
IfCondition = ([Block2_5]=1)
IfTrueAction = [!SetVariable Block2_5Color #Color#]
IfFalseAction = [!SetVariable Block2_5Color 0,0,0,0]

[Block2_6]
Measure = Calc
Formula = [MeasureBand1]>0.5
DynamicVariables = 1
IfCondition = ([Block2_6]=1)
IfTrueAction = [!SetVariable Block2_6Color #Color#]
IfFalseAction = [!SetVariable Block2_6Color 0,0,0,0]

[Block2_7]
Measure = Calc
Formula = [MeasureBand1]>0.6
DynamicVariables = 1
IfCondition = ([Block2_7]=1)
IfTrueAction = [!SetVariable Block2_7Color #Color#]
IfFalseAction = [!SetVariable Block2_7Color 0,0,0,0]

[Block2_8]
Measure = Calc
Formula = [MeasureBand1]>0.7
DynamicVariables = 1
IfCondition = ([Block2_8]=1)
IfTrueAction = [!SetVariable Block2_8Color #Color#]
IfFalseAction = [!SetVariable Block2_8Color 0,0,0,0]

[Block2_9]
Measure = Calc
Formula = [MeasureBand1]>0.8
DynamicVariables = 1
IfCondition = ([Block2_9]=1)
IfTrueAction = [!SetVariable Block2_9Color #Color#]
IfFalseAction = [!SetVariable Block2_9Color 0,0,0,0]

[Block2_10]
Measure = Calc
Formula = [MeasureBand1]>0.9
DynamicVariables = 1
IfCondition = ([Block2_10]=1)
IfTrueAction = [!SetVariable Block2_10Color #Color#]
IfFalseAction = [!SetVariable Block2_10Color 0,0,0,0]

[Block3_1]
Measure = Calc
Formula = [MeasureBand2]>0.0
DynamicVariables = 1
IfCondition = ([Block3_1]=1)
IfTrueAction = [!SetVariable Block3_1Color #Color#]
IfFalseAction = [!SetVariable Block3_1Color 0,0,0,0]

[Block3_2]
Measure = Calc
Formula = [MeasureBand2]>0.1
DynamicVariables = 1
IfCondition = ([Block3_2]=1)
IfTrueAction = [!SetVariable Block3_2Color #Color#]
IfFalseAction = [!SetVariable Block3_2Color 0,0,0,0]

[Block3_3]
Measure = Calc
Formula = [MeasureBand2]>0.2
DynamicVariables = 1
IfCondition = ([Block3_3]=1)
IfTrueAction = [!SetVariable Block3_3Color #Color#]
IfFalseAction = [!SetVariable Block3_3Color 0,0,0,0]

[Block3_4]
Measure = Calc
Formula = [MeasureBand2]>0.3
DynamicVariables = 1
IfCondition = ([Block3_4]=1)
IfTrueAction = [!SetVariable Block3_4Color #Color#]
IfFalseAction = [!SetVariable Block3_4Color 0,0,0,0]

[Block3_5]
Measure = Calc
Formula = [MeasureBand2]>0.4
DynamicVariables = 1
IfCondition = ([Block3_5]=1)
IfTrueAction = [!SetVariable Block3_5Color #Color#]
IfFalseAction = [!SetVariable Block3_5Color 0,0,0,0]

[Block3_6]
Measure = Calc
Formula = [MeasureBand2]>0.5
DynamicVariables = 1
IfCondition = ([Block3_6]=1)
IfTrueAction = [!SetVariable Block3_6Color #Color#]
IfFalseAction = [!SetVariable Block3_6Color 0,0,0,0]

[Block3_7]
Measure = Calc
Formula = [MeasureBand2]>0.6
DynamicVariables = 1
IfCondition = ([Block3_7]=1)
IfTrueAction = [!SetVariable Block3_7Color #Color#]
IfFalseAction = [!SetVariable Block3_7Color 0,0,0,0]

[Block3_8]
Measure = Calc
Formula = [MeasureBand2]>0.7
DynamicVariables = 1
IfCondition = ([Block3_8]=1)
IfTrueAction = [!SetVariable Block3_8Color #Color#]
IfFalseAction = [!SetVariable Block3_8Color 0,0,0,0]

[Block3_9]
Measure = Calc
Formula = [MeasureBand2]>0.8
DynamicVariables = 1
IfCondition = ([Block3_9]=1)
IfTrueAction = [!SetVariable Block3_9Color #Color#]
IfFalseAction = [!SetVariable Block3_9Color 0,0,0,0]

[Block3_10]
Measure = Calc
Formula = [MeasureBand2]>0.9
DynamicVariables = 1
IfCondition = ([Block3_10]=1)
IfTrueAction = [!SetVariable Block3_10Color #Color#]
IfFalseAction = [!SetVariable Block3_10Color 0,0,0,0]

[Block4_1]
Measure = Calc
Formula = [MeasureBand3]>0.0
DynamicVariables = 1
IfCondition = ([Block4_1]=1)
IfTrueAction = [!SetVariable Block4_1Color #Color#]
IfFalseAction = [!SetVariable Block4_1Color 0,0,0,0]

[Block4_2]
Measure = Calc
Formula = [MeasureBand3]>0.1
DynamicVariables = 1
IfCondition = ([Block4_2]=1)
IfTrueAction = [!SetVariable Block4_2Color #Color#]
IfFalseAction = [!SetVariable Block4_2Color 0,0,0,0]

[Block4_3]
Measure = Calc
Formula = [MeasureBand3]>0.2
DynamicVariables = 1
IfCondition = ([Block4_3]=1)
IfTrueAction = [!SetVariable Block4_3Color #Color#]
IfFalseAction = [!SetVariable Block4_3Color 0,0,0,0]

[Block4_4]
Measure = Calc
Formula = [MeasureBand3]>0.3
DynamicVariables = 1
IfCondition = ([Block4_4]=1)
IfTrueAction = [!SetVariable Block4_4Color #Color#]
IfFalseAction = [!SetVariable Block4_4Color 0,0,0,0]

[Block4_5]
Measure = Calc
Formula = [MeasureBand3]>0.4
DynamicVariables = 1
IfCondition = ([Block4_5]=1)
IfTrueAction = [!SetVariable Block4_5Color #Color#]
IfFalseAction = [!SetVariable Block4_5Color 0,0,0,0]

[Block4_6]
Measure = Calc
Formula = [MeasureBand3]>0.5
DynamicVariables = 1
IfCondition = ([Block4_6]=1)
IfTrueAction = [!SetVariable Block4_6Color #Color#]
IfFalseAction = [!SetVariable Block4_6Color 0,0,0,0]

[Block4_7]
Measure = Calc
Formula = [MeasureBand3]>0.6
DynamicVariables = 1
IfCondition = ([Block4_7]=1)
IfTrueAction = [!SetVariable Block4_7Color #Color#]
IfFalseAction = [!SetVariable Block4_7Color 0,0,0,0]

[Block4_8]
Measure = Calc
Formula = [MeasureBand3]>0.7
DynamicVariables = 1
IfCondition = ([Block4_8]=1)
IfTrueAction = [!SetVariable Block4_8Color #Color#]
IfFalseAction = [!SetVariable Block4_8Color 0,0,0,0]

[Block4_9]
Measure = Calc
Formula = [MeasureBand3]>0.8
DynamicVariables = 1
IfCondition = ([Block4_9]=1)
IfTrueAction = [!SetVariable Block4_9Color #Color#]
IfFalseAction = [!SetVariable Block4_9Color 0,0,0,0]

[Block4_10]
Measure = Calc
Formula = [MeasureBand3]>0.9
DynamicVariables = 1
IfCondition = ([Block4_10]=1)
IfTrueAction = [!SetVariable Block4_10Color #Color#]
IfFalseAction = [!SetVariable Block4_10Color 0,0,0,0]

[Block5_1]
Measure = Calc
Formula = [MeasureBand4]>0.0
DynamicVariables = 1
IfCondition = ([Block5_1]=1)
IfTrueAction = [!SetVariable Block5_1Color #Color#]
IfFalseAction = [!SetVariable Block5_1Color 0,0,0,0]

[Block5_2]
Measure = Calc
Formula = [MeasureBand4]>0.1
DynamicVariables = 1
IfCondition = ([Block5_2]=1)
IfTrueAction = [!SetVariable Block5_2Color #Color#]
IfFalseAction = [!SetVariable Block5_2Color 0,0,0,0]

[Block5_3]
Measure = Calc
Formula = [MeasureBand4]>0.2
DynamicVariables = 1
IfCondition = ([Block5_3]=1)
IfTrueAction = [!SetVariable Block5_3Color #Color#]
IfFalseAction = [!SetVariable Block5_3Color 0,0,0,0]

[Block5_4]
Measure = Calc
Formula = [MeasureBand4]>0.3
DynamicVariables = 1
IfCondition = ([Block5_4]=1)
IfTrueAction = [!SetVariable Block5_4Color #Color#]
IfFalseAction = [!SetVariable Block5_4Color 0,0,0,0]

[Block5_5]
Measure = Calc
Formula = [MeasureBand4]>0.4
DynamicVariables = 1
IfCondition = ([Block5_5]=1)
IfTrueAction = [!SetVariable Block5_5Color #Color#]
IfFalseAction = [!SetVariable Block5_5Color 0,0,0,0]

[Block5_6]
Measure = Calc
Formula = [MeasureBand4]>0.5
DynamicVariables = 1
IfCondition = ([Block5_6]=1)
IfTrueAction = [!SetVariable Block5_6Color #Color#]
IfFalseAction = [!SetVariable Block5_6Color 0,0,0,0]

[Block5_7]
Measure = Calc
Formula = [MeasureBand4]>0.6
DynamicVariables = 1
IfCondition = ([Block5_7]=1)
IfTrueAction = [!SetVariable Block5_7Color #Color#]
IfFalseAction = [!SetVariable Block5_7Color 0,0,0,0]

[Block5_8]
Measure = Calc
Formula = [MeasureBand4]>0.7
DynamicVariables = 1
IfCondition = ([Block5_8]=1)
IfTrueAction = [!SetVariable Block5_8Color #Color#]
IfFalseAction = [!SetVariable Block5_8Color 0,0,0,0]

[Block5_9]
Measure = Calc
Formula = [MeasureBand4]>0.8
DynamicVariables = 1
IfCondition = ([Block5_9]=1)
IfTrueAction = [!SetVariable Block5_9Color #Color#]
IfFalseAction = [!SetVariable Block5_9Color 0,0,0,0]

[Block5_10]
Measure = Calc
Formula = [MeasureBand4]>0.9
DynamicVariables = 1
IfCondition = ([Block5_10]=1)
IfTrueAction = [!SetVariable Block5_10Color #Color#]
IfFalseAction = [!SetVariable Block5_10Color 0,0,0,0]

[Block6_1]
Measure = Calc
Formula = [MeasureBand5]>0.0
DynamicVariables = 1
IfCondition = ([Block6_1]=1)
IfTrueAction = [!SetVariable Block6_1Color #Color#]
IfFalseAction = [!SetVariable Block6_1Color 0,0,0,0]

[Block6_2]
Measure = Calc
Formula = [MeasureBand5]>0.1
DynamicVariables = 1
IfCondition = ([Block6_2]=1)
IfTrueAction = [!SetVariable Block6_2Color #Color#]
IfFalseAction = [!SetVariable Block6_2Color 0,0,0,0]

[Block6_3]
Measure = Calc
Formula = [MeasureBand5]>0.2
DynamicVariables = 1
IfCondition = ([Block6_3]=1)
IfTrueAction = [!SetVariable Block6_3Color #Color#]
IfFalseAction = [!SetVariable Block6_3Color 0,0,0,0]

[Block6_4]
Measure = Calc
Formula = [MeasureBand5]>0.3
DynamicVariables = 1
IfCondition = ([Block6_4]=1)
IfTrueAction = [!SetVariable Block6_4Color #Color#]
IfFalseAction = [!SetVariable Block6_4Color 0,0,0,0]

[Block6_5]
Measure = Calc
Formula = [MeasureBand5]>0.4
DynamicVariables = 1
IfCondition = ([Block6_5]=1)
IfTrueAction = [!SetVariable Block6_5Color #Color#]
IfFalseAction = [!SetVariable Block6_5Color 0,0,0,0]

[Block6_6]
Measure = Calc
Formula = [MeasureBand5]>0.5
DynamicVariables = 1
IfCondition = ([Block6_6]=1)
IfTrueAction = [!SetVariable Block6_6Color #Color#]
IfFalseAction = [!SetVariable Block6_6Color 0,0,0,0]

[Block6_7]
Measure = Calc
Formula = [MeasureBand5]>0.6
DynamicVariables = 1
IfCondition = ([Block6_7]=1)
IfTrueAction = [!SetVariable Block6_7Color #Color#]
IfFalseAction = [!SetVariable Block6_7Color 0,0,0,0]

[Block6_8]
Measure = Calc
Formula = [MeasureBand5]>0.7
DynamicVariables = 1
IfCondition = ([Block6_8]=1)
IfTrueAction = [!SetVariable Block6_8Color #Color#]
IfFalseAction = [!SetVariable Block6_8Color 0,0,0,0]

[Block6_9]
Measure = Calc
Formula = [MeasureBand5]>0.8
DynamicVariables = 1
IfCondition = ([Block6_9]=1)
IfTrueAction = [!SetVariable Block6_9Color #Color#]
IfFalseAction = [!SetVariable Block6_9Color 0,0,0,0]

[Block6_10]
Measure = Calc
Formula = [MeasureBand5]>0.9
DynamicVariables = 1
IfCondition = ([Block6_10]=1)
IfTrueAction = [!SetVariable Block6_10Color #Color#]
IfFalseAction = [!SetVariable Block6_10Color 0,0,0,0]

[Block7_1]
Measure = Calc
Formula = [MeasureBand6]>0.0
DynamicVariables = 1
IfCondition = ([Block7_1]=1)
IfTrueAction = [!SetVariable Block7_1Color #Color#]
IfFalseAction = [!SetVariable Block7_1Color 0,0,0,0]

[Block7_2]
Measure = Calc
Formula = [MeasureBand6]>0.1
DynamicVariables = 1
IfCondition = ([Block7_2]=1)
IfTrueAction = [!SetVariable Block7_2Color #Color#]
IfFalseAction = [!SetVariable Block7_2Color 0,0,0,0]

[Block7_3]
Measure = Calc
Formula = [MeasureBand6]>0.2
DynamicVariables = 1
IfCondition = ([Block7_3]=1)
IfTrueAction = [!SetVariable Block7_3Color #Color#]
IfFalseAction = [!SetVariable Block7_3Color 0,0,0,0]

[Block7_4]
Measure = Calc
Formula = [MeasureBand6]>0.3
DynamicVariables = 1
IfCondition = ([Block7_4]=1)
IfTrueAction = [!SetVariable Block7_4Color #Color#]
IfFalseAction = [!SetVariable Block7_4Color 0,0,0,0]

[Block7_5]
Measure = Calc
Formula = [MeasureBand6]>0.4
DynamicVariables = 1
IfCondition = ([Block7_5]=1)
IfTrueAction = [!SetVariable Block7_5Color #Color#]
IfFalseAction = [!SetVariable Block7_5Color 0,0,0,0]

[Block7_6]
Measure = Calc
Formula = [MeasureBand6]>0.5
DynamicVariables = 1
IfCondition = ([Block7_6]=1)
IfTrueAction = [!SetVariable Block7_6Color #Color#]
IfFalseAction = [!SetVariable Block7_6Color 0,0,0,0]

[Block7_7]
Measure = Calc
Formula = [MeasureBand6]>0.6
DynamicVariables = 1
IfCondition = ([Block7_7]=1)
IfTrueAction = [!SetVariable Block7_7Color #Color#]
IfFalseAction = [!SetVariable Block7_7Color 0,0,0,0]

[Block7_8]
Measure = Calc
Formula = [MeasureBand6]>0.7
DynamicVariables = 1
IfCondition = ([Block7_8]=1)
IfTrueAction = [!SetVariable Block7_8Color #Color#]
IfFalseAction = [!SetVariable Block7_8Color 0,0,0,0]

[Block7_9]
Measure = Calc
Formula = [MeasureBand6]>0.8
DynamicVariables = 1
IfCondition = ([Block7_9]=1)
IfTrueAction = [!SetVariable Block7_9Color #Color#]
IfFalseAction = [!SetVariable Block7_9Color 0,0,0,0]

[Block7_10]
Measure = Calc
Formula = [MeasureBand6]>0.9
DynamicVariables = 1
IfCondition = ([Block7_10]=1)
IfTrueAction = [!SetVariable Block7_10Color #Color#]
IfFalseAction = [!SetVariable Block7_10Color 0,0,0,0]

[Block8_1]
Measure = Calc
Formula = [MeasureBand7]>0.0
DynamicVariables = 1
IfCondition = ([Block8_1]=1)
IfTrueAction = [!SetVariable Block8_1Color #Color#]
IfFalseAction = [!SetVariable Block8_1Color 0,0,0,0]

[Block8_2]
Measure = Calc
Formula = [MeasureBand7]>0.1
DynamicVariables = 1
IfCondition = ([Block8_2]=1)
IfTrueAction = [!SetVariable Block8_2Color #Color#]
IfFalseAction = [!SetVariable Block8_2Color 0,0,0,0]

[Block8_3]
Measure = Calc
Formula = [MeasureBand7]>0.2
DynamicVariables = 1
IfCondition = ([Block8_3]=1)
IfTrueAction = [!SetVariable Block8_3Color #Color#]
IfFalseAction = [!SetVariable Block8_3Color 0,0,0,0]

[Block8_4]
Measure = Calc
Formula = [MeasureBand7]>0.3
DynamicVariables = 1
IfCondition = ([Block8_4]=1)
IfTrueAction = [!SetVariable Block8_4Color #Color#]
IfFalseAction = [!SetVariable Block8_4Color 0,0,0,0]

[Block8_5]
Measure = Calc
Formula = [MeasureBand7]>0.4
DynamicVariables = 1
IfCondition = ([Block8_5]=1)
IfTrueAction = [!SetVariable Block8_5Color #Color#]
IfFalseAction = [!SetVariable Block8_5Color 0,0,0,0]

[Block8_6]
Measure = Calc
Formula = [MeasureBand7]>0.5
DynamicVariables = 1
IfCondition = ([Block8_6]=1)
IfTrueAction = [!SetVariable Block8_6Color #Color#]
IfFalseAction = [!SetVariable Block8_6Color 0,0,0,0]

[Block8_7]
Measure = Calc
Formula = [MeasureBand7]>0.6
DynamicVariables = 1
IfCondition = ([Block8_7]=1)
IfTrueAction = [!SetVariable Block8_7Color #Color#]
IfFalseAction = [!SetVariable Block8_7Color 0,0,0,0]

[Block8_8]
Measure = Calc
Formula = [MeasureBand7]>0.7
DynamicVariables = 1
IfCondition = ([Block8_8]=1)
IfTrueAction = [!SetVariable Block8_8Color #Color#]
IfFalseAction = [!SetVariable Block8_8Color 0,0,0,0]

[Block8_9]
Measure = Calc
Formula = [MeasureBand7]>0.8
DynamicVariables = 1
IfCondition = ([Block8_9]=1)
IfTrueAction = [!SetVariable Block8_9Color #Color#]
IfFalseAction = [!SetVariable Block8_9Color 0,0,0,0]

[Block8_10]
Measure = Calc
Formula = [MeasureBand7]>0.9
DynamicVariables = 1
IfCondition = ([Block8_10]=1)
IfTrueAction = [!SetVariable Block8_10Color #Color#]
IfFalseAction = [!SetVariable Block8_10Color 0,0,0,0]

[Block9_1]
Measure = Calc
Formula = [MeasureBand8]>0.0
DynamicVariables = 1
IfCondition = ([Block9_1]=1)
IfTrueAction = [!SetVariable Block9_1Color #Color#]
IfFalseAction = [!SetVariable Block9_1Color 0,0,0,0]

[Block9_2]
Measure = Calc
Formula = [MeasureBand8]>0.1
DynamicVariables = 1
IfCondition = ([Block9_2]=1)
IfTrueAction = [!SetVariable Block9_2Color #Color#]
IfFalseAction = [!SetVariable Block9_2Color 0,0,0,0]

[Block9_3]
Measure = Calc
Formula = [MeasureBand8]>0.2
DynamicVariables = 1
IfCondition = ([Block9_3]=1)
IfTrueAction = [!SetVariable Block9_3Color #Color#]
IfFalseAction = [!SetVariable Block9_3Color 0,0,0,0]

[Block9_4]
Measure = Calc
Formula = [MeasureBand8]>0.3
DynamicVariables = 1
IfCondition = ([Block9_4]=1)
IfTrueAction = [!SetVariable Block9_4Color #Color#]
IfFalseAction = [!SetVariable Block9_4Color 0,0,0,0]

[Block9_5]
Measure = Calc
Formula = [MeasureBand8]>0.4
DynamicVariables = 1
IfCondition = ([Block9_5]=1)
IfTrueAction = [!SetVariable Block9_5Color #Color#]
IfFalseAction = [!SetVariable Block9_5Color 0,0,0,0]

[Block9_6]
Measure = Calc
Formula = [MeasureBand8]>0.5
DynamicVariables = 1
IfCondition = ([Block9_6]=1)
IfTrueAction = [!SetVariable Block9_6Color #Color#]
IfFalseAction = [!SetVariable Block9_6Color 0,0,0,0]

[Block9_7]
Measure = Calc
Formula = [MeasureBand8]>0.6
DynamicVariables = 1
IfCondition = ([Block9_7]=1)
IfTrueAction = [!SetVariable Block9_7Color #Color#]
IfFalseAction = [!SetVariable Block9_7Color 0,0,0,0]

[Block9_8]
Measure = Calc
Formula = [MeasureBand8]>0.7
DynamicVariables = 1
IfCondition = ([Block9_8]=1)
IfTrueAction = [!SetVariable Block9_8Color #Color#]
IfFalseAction = [!SetVariable Block9_8Color 0,0,0,0]

[Block9_9]
Measure = Calc
Formula = [MeasureBand8]>0.8
DynamicVariables = 1
IfCondition = ([Block9_9]=1)
IfTrueAction = [!SetVariable Block9_9Color #Color#]
IfFalseAction = [!SetVariable Block9_9Color 0,0,0,0]

[Block9_10]
Measure = Calc
Formula = [MeasureBand8]>0.9
DynamicVariables = 1
IfCondition = ([Block9_10]=1)
IfTrueAction = [!SetVariable Block9_10Color #Color#]
IfFalseAction = [!SetVariable Block9_10Color 0,0,0,0]

[Block10_1]
Measure = Calc
Formula = [MeasureBand9]>0.0
DynamicVariables = 1
IfCondition = ([Block10_1]=1)
IfTrueAction = [!SetVariable Block10_1Color #Color#]
IfFalseAction = [!SetVariable Block10_1Color 0,0,0,0]

[Block10_2]
Measure = Calc
Formula = [MeasureBand9]>0.1
DynamicVariables = 1
IfCondition = ([Block10_2]=1)
IfTrueAction = [!SetVariable Block10_2Color #Color#]
IfFalseAction = [!SetVariable Block10_2Color 0,0,0,0]

[Block10_3]
Measure = Calc
Formula = [MeasureBand9]>0.2
DynamicVariables = 1
IfCondition = ([Block10_3]=1)
IfTrueAction = [!SetVariable Block10_3Color #Color#]
IfFalseAction = [!SetVariable Block10_3Color 0,0,0,0]

[Block10_4]
Measure = Calc
Formula = [MeasureBand9]>0.3
DynamicVariables = 1
IfCondition = ([Block10_4]=1)
IfTrueAction = [!SetVariable Block10_4Color #Color#]
IfFalseAction = [!SetVariable Block10_4Color 0,0,0,0]

[Block10_5]
Measure = Calc
Formula = [MeasureBand9]>0.4
DynamicVariables = 1
IfCondition = ([Block10_5]=1)
IfTrueAction = [!SetVariable Block10_5Color #Color#]
IfFalseAction = [!SetVariable Block10_5Color 0,0,0,0]

[Block10_6]
Measure = Calc
Formula = [MeasureBand9]>0.5
DynamicVariables = 1
IfCondition = ([Block10_6]=1)
IfTrueAction = [!SetVariable Block10_6Color #Color#]
IfFalseAction = [!SetVariable Block10_6Color 0,0,0,0]

[Block10_7]
Measure = Calc
Formula = [MeasureBand9]>0.6
DynamicVariables = 1
IfCondition = ([Block10_7]=1)
IfTrueAction = [!SetVariable Block10_7Color #Color#]
IfFalseAction = [!SetVariable Block10_7Color 0,0,0,0]

[Block10_8]
Measure = Calc
Formula = [MeasureBand9]>0.7
DynamicVariables = 1
IfCondition = ([Block10_8]=1)
IfTrueAction = [!SetVariable Block10_8Color #Color#]
IfFalseAction = [!SetVariable Block10_8Color 0,0,0,0]

[Block10_9]
Measure = Calc
Formula = [MeasureBand9]>0.8
DynamicVariables = 1
IfCondition = ([Block10_9]=1)
IfTrueAction = [!SetVariable Block10_9Color #Color#]
IfFalseAction = [!SetVariable Block10_9Color 0,0,0,0]

[Block10_10]
Measure = Calc
Formula = [MeasureBand9]>0.9
DynamicVariables = 1
IfCondition = ([Block10_10]=1)
IfTrueAction = [!SetVariable Block10_10Color #Color#]
IfFalseAction = [!SetVariable Block10_10Color 0,0,0,0]

[Block11_1]
Measure = Calc
Formula = [MeasureBand10]>0.0
DynamicVariables = 1
IfCondition = ([Block11_1]=1)
IfTrueAction = [!SetVariable Block11_1Color #Color#]
IfFalseAction = [!SetVariable Block11_1Color 0,0,0,0]

[Block11_2]
Measure = Calc
Formula = [MeasureBand10]>0.1
DynamicVariables = 1
IfCondition = ([Block11_2]=1)
IfTrueAction = [!SetVariable Block11_2Color #Color#]
IfFalseAction = [!SetVariable Block11_2Color 0,0,0,0]

[Block11_3]
Measure = Calc
Formula = [MeasureBand10]>0.2
DynamicVariables = 1
IfCondition = ([Block11_3]=1)
IfTrueAction = [!SetVariable Block11_3Color #Color#]
IfFalseAction = [!SetVariable Block11_3Color 0,0,0,0]

[Block11_4]
Measure = Calc
Formula = [MeasureBand10]>0.3
DynamicVariables = 1
IfCondition = ([Block11_4]=1)
IfTrueAction = [!SetVariable Block11_4Color #Color#]
IfFalseAction = [!SetVariable Block11_4Color 0,0,0,0]

[Block11_5]
Measure = Calc
Formula = [MeasureBand10]>0.4
DynamicVariables = 1
IfCondition = ([Block11_5]=1)
IfTrueAction = [!SetVariable Block11_5Color #Color#]
IfFalseAction = [!SetVariable Block11_5Color 0,0,0,0]

[Block11_6]
Measure = Calc
Formula = [MeasureBand10]>0.5
DynamicVariables = 1
IfCondition = ([Block11_6]=1)
IfTrueAction = [!SetVariable Block11_6Color #Color#]
IfFalseAction = [!SetVariable Block11_6Color 0,0,0,0]

[Block11_7]
Measure = Calc
Formula = [MeasureBand10]>0.6
DynamicVariables = 1
IfCondition = ([Block11_7]=1)
IfTrueAction = [!SetVariable Block11_7Color #Color#]
IfFalseAction = [!SetVariable Block11_7Color 0,0,0,0]

[Block11_8]
Measure = Calc
Formula = [MeasureBand10]>0.7
DynamicVariables = 1
IfCondition = ([Block11_8]=1)
IfTrueAction = [!SetVariable Block11_8Color #Color#]
IfFalseAction = [!SetVariable Block11_8Color 0,0,0,0]

[Block11_9]
Measure = Calc
Formula = [MeasureBand10]>0.8
DynamicVariables = 1
IfCondition = ([Block11_9]=1)
IfTrueAction = [!SetVariable Block11_9Color #Color#]
IfFalseAction = [!SetVariable Block11_9Color 0,0,0,0]

[Block11_10]
Measure = Calc
Formula = [MeasureBand10]>0.9
DynamicVariables = 1
IfCondition = ([Block11_10]=1)
IfTrueAction = [!SetVariable Block11_10Color #Color#]
IfFalseAction = [!SetVariable Block11_10Color 0,0,0,0]

[Block12_1]
Measure = Calc
Formula = [MeasureBand11]>0.0
DynamicVariables = 1
IfCondition = ([Block12_1]=1)
IfTrueAction = [!SetVariable Block12_1Color #Color#]
IfFalseAction = [!SetVariable Block12_1Color 0,0,0,0]

[Block12_2]
Measure = Calc
Formula = [MeasureBand11]>0.1
DynamicVariables = 1
IfCondition = ([Block12_2]=1)
IfTrueAction = [!SetVariable Block12_2Color #Color#]
IfFalseAction = [!SetVariable Block12_2Color 0,0,0,0]

[Block12_3]
Measure = Calc
Formula = [MeasureBand11]>0.2
DynamicVariables = 1
IfCondition = ([Block12_3]=1)
IfTrueAction = [!SetVariable Block12_3Color #Color#]
IfFalseAction = [!SetVariable Block12_3Color 0,0,0,0]

[Block12_4]
Measure = Calc
Formula = [MeasureBand11]>0.3
DynamicVariables = 1
IfCondition = ([Block12_4]=1)
IfTrueAction = [!SetVariable Block12_4Color #Color#]
IfFalseAction = [!SetVariable Block12_4Color 0,0,0,0]

[Block12_5]
Measure = Calc
Formula = [MeasureBand11]>0.4
DynamicVariables = 1
IfCondition = ([Block12_5]=1)
IfTrueAction = [!SetVariable Block12_5Color #Color#]
IfFalseAction = [!SetVariable Block12_5Color 0,0,0,0]

[Block12_6]
Measure = Calc
Formula = [MeasureBand11]>0.5
DynamicVariables = 1
IfCondition = ([Block12_6]=1)
IfTrueAction = [!SetVariable Block12_6Color #Color#]
IfFalseAction = [!SetVariable Block12_6Color 0,0,0,0]

[Block12_7]
Measure = Calc
Formula = [MeasureBand11]>0.6
DynamicVariables = 1
IfCondition = ([Block12_7]=1)
IfTrueAction = [!SetVariable Block12_7Color #Color#]
IfFalseAction = [!SetVariable Block12_7Color 0,0,0,0]

[Block12_8]
Measure = Calc
Formula = [MeasureBand11]>0.7
DynamicVariables = 1
IfCondition = ([Block12_8]=1)
IfTrueAction = [!SetVariable Block12_8Color #Color#]
IfFalseAction = [!SetVariable Block12_8Color 0,0,0,0]

[Block12_9]
Measure = Calc
Formula = [MeasureBand11]>0.8
DynamicVariables = 1
IfCondition = ([Block12_9]=1)
IfTrueAction = [!SetVariable Block12_9Color #Color#]
IfFalseAction = [!SetVariable Block12_9Color 0,0,0,0]

[Block12_10]
Measure = Calc
Formula = [MeasureBand11]>0.9
DynamicVariables = 1
IfCondition = ([Block12_10]=1)
IfTrueAction = [!SetVariable Block12_10Color #Color#]
IfFalseAction = [!SetVariable Block12_10Color 0,0,0,0]

[Block13_1]
Measure = Calc
Formula = [MeasureBand12]>0.0
DynamicVariables = 1
IfCondition = ([Block13_1]=1)
IfTrueAction = [!SetVariable Block13_1Color #Color#]
IfFalseAction = [!SetVariable Block13_1Color 0,0,0,0]

[Block13_2]
Measure = Calc
Formula = [MeasureBand12]>0.1
DynamicVariables = 1
IfCondition = ([Block13_2]=1)
IfTrueAction = [!SetVariable Block13_2Color #Color#]
IfFalseAction = [!SetVariable Block13_2Color 0,0,0,0]

[Block13_3]
Measure = Calc
Formula = [MeasureBand12]>0.2
DynamicVariables = 1
IfCondition = ([Block13_3]=1)
IfTrueAction = [!SetVariable Block13_3Color #Color#]
IfFalseAction = [!SetVariable Block13_3Color 0,0,0,0]

[Block13_4]
Measure = Calc
Formula = [MeasureBand12]>0.3
DynamicVariables = 1
IfCondition = ([Block13_4]=1)
IfTrueAction = [!SetVariable Block13_4Color #Color#]
IfFalseAction = [!SetVariable Block13_4Color 0,0,0,0]

[Block13_5]
Measure = Calc
Formula = [MeasureBand12]>0.4
DynamicVariables = 1
IfCondition = ([Block13_5]=1)
IfTrueAction = [!SetVariable Block13_5Color #Color#]
IfFalseAction = [!SetVariable Block13_5Color 0,0,0,0]

[Block13_6]
Measure = Calc
Formula = [MeasureBand12]>0.5
DynamicVariables = 1
IfCondition = ([Block13_6]=1)
IfTrueAction = [!SetVariable Block13_6Color #Color#]
IfFalseAction = [!SetVariable Block13_6Color 0,0,0,0]

[Block13_7]
Measure = Calc
Formula = [MeasureBand12]>0.6
DynamicVariables = 1
IfCondition = ([Block13_7]=1)
IfTrueAction = [!SetVariable Block13_7Color #Color#]
IfFalseAction = [!SetVariable Block13_7Color 0,0,0,0]

[Block13_8]
Measure = Calc
Formula = [MeasureBand12]>0.7
DynamicVariables = 1
IfCondition = ([Block13_8]=1)
IfTrueAction = [!SetVariable Block13_8Color #Color#]
IfFalseAction = [!SetVariable Block13_8Color 0,0,0,0]

[Block13_9]
Measure = Calc
Formula = [MeasureBand12]>0.8
DynamicVariables = 1
IfCondition = ([Block13_9]=1)
IfTrueAction = [!SetVariable Block13_9Color #Color#]
IfFalseAction = [!SetVariable Block13_9Color 0,0,0,0]

[Block13_10]
Measure = Calc
Formula = [MeasureBand12]>0.9
DynamicVariables = 1
IfCondition = ([Block13_10]=1)
IfTrueAction = [!SetVariable Block13_10Color #Color#]
IfFalseAction = [!SetVariable Block13_10Color 0,0,0,0]

[Block14_1]
Measure = Calc
Formula = [MeasureBand13]>0.0
DynamicVariables = 1
IfCondition = ([Block14_1]=1)
IfTrueAction = [!SetVariable Block14_1Color #Color#]
IfFalseAction = [!SetVariable Block14_1Color 0,0,0,0]

[Block14_2]
Measure = Calc
Formula = [MeasureBand13]>0.1
DynamicVariables = 1
IfCondition = ([Block14_2]=1)
IfTrueAction = [!SetVariable Block14_2Color #Color#]
IfFalseAction = [!SetVariable Block14_2Color 0,0,0,0]

[Block14_3]
Measure = Calc
Formula = [MeasureBand13]>0.2
DynamicVariables = 1
IfCondition = ([Block14_3]=1)
IfTrueAction = [!SetVariable Block14_3Color #Color#]
IfFalseAction = [!SetVariable Block14_3Color 0,0,0,0]

[Block14_4]
Measure = Calc
Formula = [MeasureBand13]>0.3
DynamicVariables = 1
IfCondition = ([Block14_4]=1)
IfTrueAction = [!SetVariable Block14_4Color #Color#]
IfFalseAction = [!SetVariable Block14_4Color 0,0,0,0]

[Block14_5]
Measure = Calc
Formula = [MeasureBand13]>0.4
DynamicVariables = 1
IfCondition = ([Block14_5]=1)
IfTrueAction = [!SetVariable Block14_5Color #Color#]
IfFalseAction = [!SetVariable Block14_5Color 0,0,0,0]

[Block14_6]
Measure = Calc
Formula = [MeasureBand13]>0.5
DynamicVariables = 1
IfCondition = ([Block14_6]=1)
IfTrueAction = [!SetVariable Block14_6Color #Color#]
IfFalseAction = [!SetVariable Block14_6Color 0,0,0,0]

[Block14_7]
Measure = Calc
Formula = [MeasureBand13]>0.6
DynamicVariables = 1
IfCondition = ([Block14_7]=1)
IfTrueAction = [!SetVariable Block14_7Color #Color#]
IfFalseAction = [!SetVariable Block14_7Color 0,0,0,0]

[Block14_8]
Measure = Calc
Formula = [MeasureBand13]>0.7
DynamicVariables = 1
IfCondition = ([Block14_8]=1)
IfTrueAction = [!SetVariable Block14_8Color #Color#]
IfFalseAction = [!SetVariable Block14_8Color 0,0,0,0]

[Block14_9]
Measure = Calc
Formula = [MeasureBand13]>0.8
DynamicVariables = 1
IfCondition = ([Block14_9]=1)
IfTrueAction = [!SetVariable Block14_9Color #Color#]
IfFalseAction = [!SetVariable Block14_9Color 0,0,0,0]

[Block14_10]
Measure = Calc
Formula = [MeasureBand13]>0.9
DynamicVariables = 1
IfCondition = ([Block14_10]=1)
IfTrueAction = [!SetVariable Block14_10Color #Color#]
IfFalseAction = [!SetVariable Block14_10Color 0,0,0,0]

[Block15_1]
Measure = Calc
Formula = [MeasureBand14]>0.0
DynamicVariables = 1
IfCondition = ([Block15_1]=1)
IfTrueAction = [!SetVariable Block15_1Color #Color#]
IfFalseAction = [!SetVariable Block15_1Color 0,0,0,0]

[Block15_2]
Measure = Calc
Formula = [MeasureBand14]>0.1
DynamicVariables = 1
IfCondition = ([Block15_2]=1)
IfTrueAction = [!SetVariable Block15_2Color #Color#]
IfFalseAction = [!SetVariable Block15_2Color 0,0,0,0]

[Block15_3]
Measure = Calc
Formula = [MeasureBand14]>0.2
DynamicVariables = 1
IfCondition = ([Block15_3]=1)
IfTrueAction = [!SetVariable Block15_3Color #Color#]
IfFalseAction = [!SetVariable Block15_3Color 0,0,0,0]

[Block15_4]
Measure = Calc
Formula = [MeasureBand14]>0.3
DynamicVariables = 1
IfCondition = ([Block15_4]=1)
IfTrueAction = [!SetVariable Block15_4Color #Color#]
IfFalseAction = [!SetVariable Block15_4Color 0,0,0,0]

[Block15_5]
Measure = Calc
Formula = [MeasureBand14]>0.4
DynamicVariables = 1
IfCondition = ([Block15_5]=1)
IfTrueAction = [!SetVariable Block15_5Color #Color#]
IfFalseAction = [!SetVariable Block15_5Color 0,0,0,0]

[Block15_6]
Measure = Calc
Formula = [MeasureBand14]>0.5
DynamicVariables = 1
IfCondition = ([Block15_6]=1)
IfTrueAction = [!SetVariable Block15_6Color #Color#]
IfFalseAction = [!SetVariable Block15_6Color 0,0,0,0]

[Block15_7]
Measure = Calc
Formula = [MeasureBand14]>0.6
DynamicVariables = 1
IfCondition = ([Block15_7]=1)
IfTrueAction = [!SetVariable Block15_7Color #Color#]
IfFalseAction = [!SetVariable Block15_7Color 0,0,0,0]

[Block15_8]
Measure = Calc
Formula = [MeasureBand14]>0.7
DynamicVariables = 1
IfCondition = ([Block15_8]=1)
IfTrueAction = [!SetVariable Block15_8Color #Color#]
IfFalseAction = [!SetVariable Block15_8Color 0,0,0,0]

[Block15_9]
Measure = Calc
Formula = [MeasureBand14]>0.8
DynamicVariables = 1
IfCondition = ([Block15_9]=1)
IfTrueAction = [!SetVariable Block15_9Color #Color#]
IfFalseAction = [!SetVariable Block15_9Color 0,0,0,0]

[Block15_10]
Measure = Calc
Formula = [MeasureBand14]>0.9
DynamicVariables = 1
IfCondition = ([Block15_10]=1)
IfTrueAction = [!SetVariable Block15_10Color #Color#]
IfFalseAction = [!SetVariable Block15_10Color 0,0,0,0]

[Block16_1]
Measure = Calc
Formula = [MeasureBand15]>0.0
DynamicVariables = 1
IfCondition = ([Block16_1]=1)
IfTrueAction = [!SetVariable Block16_1Color #Color#]
IfFalseAction = [!SetVariable Block16_1Color 0,0,0,0]

[Block16_2]
Measure = Calc
Formula = [MeasureBand15]>0.1
DynamicVariables = 1
IfCondition = ([Block16_2]=1)
IfTrueAction = [!SetVariable Block16_2Color #Color#]
IfFalseAction = [!SetVariable Block16_2Color 0,0,0,0]

[Block16_3]
Measure = Calc
Formula = [MeasureBand15]>0.2
DynamicVariables = 1
IfCondition = ([Block16_3]=1)
IfTrueAction = [!SetVariable Block16_3Color #Color#]
IfFalseAction = [!SetVariable Block16_3Color 0,0,0,0]

[Block16_4]
Measure = Calc
Formula = [MeasureBand15]>0.3
DynamicVariables = 1
IfCondition = ([Block16_4]=1)
IfTrueAction = [!SetVariable Block16_4Color #Color#]
IfFalseAction = [!SetVariable Block16_4Color 0,0,0,0]

[Block16_5]
Measure = Calc
Formula = [MeasureBand15]>0.4
DynamicVariables = 1
IfCondition = ([Block16_5]=1)
IfTrueAction = [!SetVariable Block16_5Color #Color#]
IfFalseAction = [!SetVariable Block16_5Color 0,0,0,0]

[Block16_6]
Measure = Calc
Formula = [MeasureBand15]>0.5
DynamicVariables = 1
IfCondition = ([Block16_6]=1)
IfTrueAction = [!SetVariable Block16_6Color #Color#]
IfFalseAction = [!SetVariable Block16_6Color 0,0,0,0]

[Block16_7]
Measure = Calc
Formula = [MeasureBand15]>0.6
DynamicVariables = 1
IfCondition = ([Block16_7]=1)
IfTrueAction = [!SetVariable Block16_7Color #Color#]
IfFalseAction = [!SetVariable Block16_7Color 0,0,0,0]

[Block16_8]
Measure = Calc
Formula = [MeasureBand15]>0.7
DynamicVariables = 1
IfCondition = ([Block16_8]=1)
IfTrueAction = [!SetVariable Block16_8Color #Color#]
IfFalseAction = [!SetVariable Block16_8Color 0,0,0,0]

[Block16_9]
Measure = Calc
Formula = [MeasureBand15]>0.8
DynamicVariables = 1
IfCondition = ([Block16_9]=1)
IfTrueAction = [!SetVariable Block16_9Color #Color#]
IfFalseAction = [!SetVariable Block16_9Color 0,0,0,0]

[Block16_10]
Measure = Calc
Formula = [MeasureBand15]>0.9
DynamicVariables = 1
IfCondition = ([Block16_10]=1)
IfTrueAction = [!SetVariable Block16_10Color #Color#]
IfFalseAction = [!SetVariable Block16_10Color 0,0,0,0]

[Block17_1]
Measure = Calc
Formula = [MeasureBand16]>0.0
DynamicVariables = 1
IfCondition = ([Block17_1]=1)
IfTrueAction = [!SetVariable Block17_1Color #Color#]
IfFalseAction = [!SetVariable Block17_1Color 0,0,0,0]

[Block17_2]
Measure = Calc
Formula = [MeasureBand16]>0.1
DynamicVariables = 1
IfCondition = ([Block17_2]=1)
IfTrueAction = [!SetVariable Block17_2Color #Color#]
IfFalseAction = [!SetVariable Block17_2Color 0,0,0,0]

[Block17_3]
Measure = Calc
Formula = [MeasureBand16]>0.2
DynamicVariables = 1
IfCondition = ([Block17_3]=1)
IfTrueAction = [!SetVariable Block17_3Color #Color#]
IfFalseAction = [!SetVariable Block17_3Color 0,0,0,0]

[Block17_4]
Measure = Calc
Formula = [MeasureBand16]>0.3
DynamicVariables = 1
IfCondition = ([Block17_4]=1)
IfTrueAction = [!SetVariable Block17_4Color #Color#]
IfFalseAction = [!SetVariable Block17_4Color 0,0,0,0]

[Block17_5]
Measure = Calc
Formula = [MeasureBand16]>0.4
DynamicVariables = 1
IfCondition = ([Block17_5]=1)
IfTrueAction = [!SetVariable Block17_5Color #Color#]
IfFalseAction = [!SetVariable Block17_5Color 0,0,0,0]

[Block17_6]
Measure = Calc
Formula = [MeasureBand16]>0.5
DynamicVariables = 1
IfCondition = ([Block17_6]=1)
IfTrueAction = [!SetVariable Block17_6Color #Color#]
IfFalseAction = [!SetVariable Block17_6Color 0,0,0,0]

[Block17_7]
Measure = Calc
Formula = [MeasureBand16]>0.6
DynamicVariables = 1
IfCondition = ([Block17_7]=1)
IfTrueAction = [!SetVariable Block17_7Color #Color#]
IfFalseAction = [!SetVariable Block17_7Color 0,0,0,0]

[Block17_8]
Measure = Calc
Formula = [MeasureBand16]>0.7
DynamicVariables = 1
IfCondition = ([Block17_8]=1)
IfTrueAction = [!SetVariable Block17_8Color #Color#]
IfFalseAction = [!SetVariable Block17_8Color 0,0,0,0]

[Block17_9]
Measure = Calc
Formula = [MeasureBand16]>0.8
DynamicVariables = 1
IfCondition = ([Block17_9]=1)
IfTrueAction = [!SetVariable Block17_9Color #Color#]
IfFalseAction = [!SetVariable Block17_9Color 0,0,0,0]

[Block17_10]
Measure = Calc
Formula = [MeasureBand16]>0.9
DynamicVariables = 1
IfCondition = ([Block17_10]=1)
IfTrueAction = [!SetVariable Block17_10Color #Color#]
IfFalseAction = [!SetVariable Block17_10Color 0,0,0,0]

[Block18_1]
Measure = Calc
Formula = [MeasureBand17]>0.0
DynamicVariables = 1
IfCondition = ([Block18_1]=1)
IfTrueAction = [!SetVariable Block18_1Color #Color#]
IfFalseAction = [!SetVariable Block18_1Color 0,0,0,0]

[Block18_2]
Measure = Calc
Formula = [MeasureBand17]>0.1
DynamicVariables = 1
IfCondition = ([Block18_2]=1)
IfTrueAction = [!SetVariable Block18_2Color #Color#]
IfFalseAction = [!SetVariable Block18_2Color 0,0,0,0]

[Block18_3]
Measure = Calc
Formula = [MeasureBand17]>0.2
DynamicVariables = 1
IfCondition = ([Block18_3]=1)
IfTrueAction = [!SetVariable Block18_3Color #Color#]
IfFalseAction = [!SetVariable Block18_3Color 0,0,0,0]

[Block18_4]
Measure = Calc
Formula = [MeasureBand17]>0.3
DynamicVariables = 1
IfCondition = ([Block18_4]=1)
IfTrueAction = [!SetVariable Block18_4Color #Color#]
IfFalseAction = [!SetVariable Block18_4Color 0,0,0,0]

[Block18_5]
Measure = Calc
Formula = [MeasureBand17]>0.4
DynamicVariables = 1
IfCondition = ([Block18_5]=1)
IfTrueAction = [!SetVariable Block18_5Color #Color#]
IfFalseAction = [!SetVariable Block18_5Color 0,0,0,0]

[Block18_6]
Measure = Calc
Formula = [MeasureBand17]>0.5
DynamicVariables = 1
IfCondition = ([Block18_6]=1)
IfTrueAction = [!SetVariable Block18_6Color #Color#]
IfFalseAction = [!SetVariable Block18_6Color 0,0,0,0]

[Block18_7]
Measure = Calc
Formula = [MeasureBand17]>0.6
DynamicVariables = 1
IfCondition = ([Block18_7]=1)
IfTrueAction = [!SetVariable Block18_7Color #Color#]
IfFalseAction = [!SetVariable Block18_7Color 0,0,0,0]

[Block18_8]
Measure = Calc
Formula = [MeasureBand17]>0.7
DynamicVariables = 1
IfCondition = ([Block18_8]=1)
IfTrueAction = [!SetVariable Block18_8Color #Color#]
IfFalseAction = [!SetVariable Block18_8Color 0,0,0,0]

[Block18_9]
Measure = Calc
Formula = [MeasureBand17]>0.8
DynamicVariables = 1
IfCondition = ([Block18_9]=1)
IfTrueAction = [!SetVariable Block18_9Color #Color#]
IfFalseAction = [!SetVariable Block18_9Color 0,0,0,0]

[Block18_10]
Measure = Calc
Formula = [MeasureBand17]>0.9
DynamicVariables = 1
IfCondition = ([Block18_10]=1)
IfTrueAction = [!SetVariable Block18_10Color #Color#]
IfFalseAction = [!SetVariable Block18_10Color 0,0,0,0]

[Block19_1]
Measure = Calc
Formula = [MeasureBand18]>0.0
DynamicVariables = 1
IfCondition = ([Block19_1]=1)
IfTrueAction = [!SetVariable Block19_1Color #Color#]
IfFalseAction = [!SetVariable Block19_1Color 0,0,0,0]

[Block19_2]
Measure = Calc
Formula = [MeasureBand18]>0.1
DynamicVariables = 1
IfCondition = ([Block19_2]=1)
IfTrueAction = [!SetVariable Block19_2Color #Color#]
IfFalseAction = [!SetVariable Block19_2Color 0,0,0,0]

[Block19_3]
Measure = Calc
Formula = [MeasureBand18]>0.2
DynamicVariables = 1
IfCondition = ([Block19_3]=1)
IfTrueAction = [!SetVariable Block19_3Color #Color#]
IfFalseAction = [!SetVariable Block19_3Color 0,0,0,0]

[Block19_4]
Measure = Calc
Formula = [MeasureBand18]>0.3
DynamicVariables = 1
IfCondition = ([Block19_4]=1)
IfTrueAction = [!SetVariable Block19_4Color #Color#]
IfFalseAction = [!SetVariable Block19_4Color 0,0,0,0]

[Block19_5]
Measure = Calc
Formula = [MeasureBand18]>0.4
DynamicVariables = 1
IfCondition = ([Block19_5]=1)
IfTrueAction = [!SetVariable Block19_5Color #Color#]
IfFalseAction = [!SetVariable Block19_5Color 0,0,0,0]

[Block19_6]
Measure = Calc
Formula = [MeasureBand18]>0.5
DynamicVariables = 1
IfCondition = ([Block19_6]=1)
IfTrueAction = [!SetVariable Block19_6Color #Color#]
IfFalseAction = [!SetVariable Block19_6Color 0,0,0,0]

[Block19_7]
Measure = Calc
Formula = [MeasureBand18]>0.6
DynamicVariables = 1
IfCondition = ([Block19_7]=1)
IfTrueAction = [!SetVariable Block19_7Color #Color#]
IfFalseAction = [!SetVariable Block19_7Color 0,0,0,0]

[Block19_8]
Measure = Calc
Formula = [MeasureBand18]>0.7
DynamicVariables = 1
IfCondition = ([Block19_8]=1)
IfTrueAction = [!SetVariable Block19_8Color #Color#]
IfFalseAction = [!SetVariable Block19_8Color 0,0,0,0]

[Block19_9]
Measure = Calc
Formula = [MeasureBand18]>0.8
DynamicVariables = 1
IfCondition = ([Block19_9]=1)
IfTrueAction = [!SetVariable Block19_9Color #Color#]
IfFalseAction = [!SetVariable Block19_9Color 0,0,0,0]

[Block19_10]
Measure = Calc
Formula = [MeasureBand18]>0.9
DynamicVariables = 1
IfCondition = ([Block19_10]=1)
IfTrueAction = [!SetVariable Block19_10Color #Color#]
IfFalseAction = [!SetVariable Block19_10Color 0,0,0,0]

[Block20_1]
Measure = Calc
Formula = [MeasureBand19]>0.0
DynamicVariables = 1
IfCondition = ([Block20_1]=1)
IfTrueAction = [!SetVariable Block20_1Color #Color#]
IfFalseAction = [!SetVariable Block20_1Color 0,0,0,0]

[Block20_2]
Measure = Calc
Formula = [MeasureBand19]>0.1
DynamicVariables = 1
IfCondition = ([Block20_2]=1)
IfTrueAction = [!SetVariable Block20_2Color #Color#]
IfFalseAction = [!SetVariable Block20_2Color 0,0,0,0]

[Block20_3]
Measure = Calc
Formula = [MeasureBand19]>0.2
DynamicVariables = 1
IfCondition = ([Block20_3]=1)
IfTrueAction = [!SetVariable Block20_3Color #Color#]
IfFalseAction = [!SetVariable Block20_3Color 0,0,0,0]

[Block20_4]
Measure = Calc
Formula = [MeasureBand19]>0.3
DynamicVariables = 1
IfCondition = ([Block20_4]=1)
IfTrueAction = [!SetVariable Block20_4Color #Color#]
IfFalseAction = [!SetVariable Block20_4Color 0,0,0,0]

[Block20_5]
Measure = Calc
Formula = [MeasureBand19]>0.4
DynamicVariables = 1
IfCondition = ([Block20_5]=1)
IfTrueAction = [!SetVariable Block20_5Color #Color#]
IfFalseAction = [!SetVariable Block20_5Color 0,0,0,0]

[Block20_6]
Measure = Calc
Formula = [MeasureBand19]>0.5
DynamicVariables = 1
IfCondition = ([Block20_6]=1)
IfTrueAction = [!SetVariable Block20_6Color #Color#]
IfFalseAction = [!SetVariable Block20_6Color 0,0,0,0]

[Block20_7]
Measure = Calc
Formula = [MeasureBand19]>0.6
DynamicVariables = 1
IfCondition = ([Block20_7]=1)
IfTrueAction = [!SetVariable Block20_7Color #Color#]
IfFalseAction = [!SetVariable Block20_7Color 0,0,0,0]

[Block20_8]
Measure = Calc
Formula = [MeasureBand19]>0.7
DynamicVariables = 1
IfCondition = ([Block20_8]=1)
IfTrueAction = [!SetVariable Block20_8Color #Color#]
IfFalseAction = [!SetVariable Block20_8Color 0,0,0,0]

[Block20_9]
Measure = Calc
Formula = [MeasureBand19]>0.8
DynamicVariables = 1
IfCondition = ([Block20_9]=1)
IfTrueAction = [!SetVariable Block20_9Color #Color#]
IfFalseAction = [!SetVariable Block20_9Color 0,0,0,0]

[Block20_10]
Measure = Calc
Formula = [MeasureBand19]>0.9
DynamicVariables = 1
IfCondition = ([Block20_10]=1)
IfTrueAction = [!SetVariable Block20_10Color #Color#]
IfFalseAction = [!SetVariable Block20_10Color 0,0,0,0]

[Block21_1]
Measure = Calc
Formula = [MeasureBand20]>0.0
DynamicVariables = 1
IfCondition = ([Block21_1]=1)
IfTrueAction = [!SetVariable Block21_1Color #Color#]
IfFalseAction = [!SetVariable Block21_1Color 0,0,0,0]

[Block21_2]
Measure = Calc
Formula = [MeasureBand20]>0.1
DynamicVariables = 1
IfCondition = ([Block21_2]=1)
IfTrueAction = [!SetVariable Block21_2Color #Color#]
IfFalseAction = [!SetVariable Block21_2Color 0,0,0,0]

[Block21_3]
Measure = Calc
Formula = [MeasureBand20]>0.2
DynamicVariables = 1
IfCondition = ([Block21_3]=1)
IfTrueAction = [!SetVariable Block21_3Color #Color#]
IfFalseAction = [!SetVariable Block21_3Color 0,0,0,0]

[Block21_4]
Measure = Calc
Formula = [MeasureBand20]>0.3
DynamicVariables = 1
IfCondition = ([Block21_4]=1)
IfTrueAction = [!SetVariable Block21_4Color #Color#]
IfFalseAction = [!SetVariable Block21_4Color 0,0,0,0]

[Block21_5]
Measure = Calc
Formula = [MeasureBand20]>0.4
DynamicVariables = 1
IfCondition = ([Block21_5]=1)
IfTrueAction = [!SetVariable Block21_5Color #Color#]
IfFalseAction = [!SetVariable Block21_5Color 0,0,0,0]

[Block21_6]
Measure = Calc
Formula = [MeasureBand20]>0.5
DynamicVariables = 1
IfCondition = ([Block21_6]=1)
IfTrueAction = [!SetVariable Block21_6Color #Color#]
IfFalseAction = [!SetVariable Block21_6Color 0,0,0,0]

[Block21_7]
Measure = Calc
Formula = [MeasureBand20]>0.6
DynamicVariables = 1
IfCondition = ([Block21_7]=1)
IfTrueAction = [!SetVariable Block21_7Color #Color#]
IfFalseAction = [!SetVariable Block21_7Color 0,0,0,0]

[Block21_8]
Measure = Calc
Formula = [MeasureBand20]>0.7
DynamicVariables = 1
IfCondition = ([Block21_8]=1)
IfTrueAction = [!SetVariable Block21_8Color #Color#]
IfFalseAction = [!SetVariable Block21_8Color 0,0,0,0]

[Block21_9]
Measure = Calc
Formula = [MeasureBand20]>0.8
DynamicVariables = 1
IfCondition= ([Block21_9]=1)
IfTrueAction = [!SetVariable Block21_9Color #Color#]
IfFalseAction = [!SetVariable Block21_9Color 0,0,0,0]

[Block21_10]
Measure = Calc
Formula = [MeasureBand20]>0.9
DynamicVariables = 1
IfCondition = ([Block21_10]=1)
IfTrueAction = [!SetVariable Block21_10Color #Color#]
IfFalseAction = [!SetVariable Block21_10Color 0,0,0,0]

[Block22_1]
Measure = Calc
Formula = [MeasureBand21]>0.0
DynamicVariables = 1
IfCondition = ([Block22_1]=1)
IfTrueAction = [!SetVariable Block22_1Color #Color#]
IfFalseAction = [!SetVariable Block22_1Color 0,0,0,0]

[Block22_2]
Measure = Calc
Formula = [MeasureBand21]>0.1
DynamicVariables = 1
IfCondition = ([Block22_2]=1)
IfTrueAction = [!SetVariable Block22_2Color #Color#]
IfFalseAction = [!SetVariable Block22_2Color 0,0,0,0]

[Block22_3]
Measure = Calc
Formula = [MeasureBand21]>0.2
DynamicVariables = 1
IfCondition = ([Block22_3]=1)
IfTrueAction = [!SetVariable Block22_3Color #Color#]
IfFalseAction = [!SetVariable Block22_3Color 0,0,0,0]

[Block22_4]
Measure = Calc
Formula = [MeasureBand21]>0.3
DynamicVariables = 1
IfCondition = ([Block22_4]=1)
IfTrueAction = [!SetVariable Block22_4Color #Color#]
IfFalseAction = [!SetVariable Block22_4Color 0,0,0,0]

[Block22_5]
Measure = Calc
Formula = [MeasureBand21]>0.4
DynamicVariables = 1
IfCondition = ([Block22_5]=1)
IfTrueAction = [!SetVariable Block22_5Color #Color#]
IfFalseAction = [!SetVariable Block22_5Color 0,0,0,0]

[Block22_6]
Measure = Calc
Formula = [MeasureBand21]>0.5
DynamicVariables = 1
IfCondition = ([Block22_6]=1)
IfTrueAction = [!SetVariable Block22_6Color #Color#]
IfFalseAction = [!SetVariable Block22_6Color 0,0,0,0]

[Block22_7]
Measure = Calc
Formula = [MeasureBand21]>0.6
DynamicVariables = 1
IfCondition = ([Block22_7]=1)
IfTrueAction = [!SetVariable Block22_7Color #Color#]
IfFalseAction = [!SetVariable Block22_7Color 0,0,0,0]

[Block22_8]
Measure = Calc
Formula = [MeasureBand21]>0.7
DynamicVariables = 1
IfCondition = ([Block22_8]=1)
IfTrueAction = [!SetVariable Block22_8Color #Color#]
IfFalseAction = [!SetVariable Block22_8Color 0,0,0,0]

[Block22_9]
Measure = Calc
Formula = [MeasureBand21]>0.8
DynamicVariables = 1
IfCondition = ([Block22_9]=1)
IfTrueAction = [!SetVariable Block22_9Color #Color#]
IfFalseAction = [!SetVariable Block22_9Color 0,0,0,0]

[Block22_10]
Measure = Calc
Formula = [MeasureBand21]>0.9
DynamicVariables = 1
IfCondition = ([Block22_10]=1)
IfTrueAction = [!SetVariable Block22_10Color #Color#]
IfFalseAction = [!SetVariable Block22_10Color 0,0,0,0]

[Block23_1]
Measure = Calc
Formula = [MeasureBand22]>0.0
DynamicVariables = 1
IfCondition = ([Block23_1]=1)
IfTrueAction = [!SetVariable Block23_1Color #Color#]
IfFalseAction = [!SetVariable Block23_1Color 0,0,0,0]

[Block23_2]
Measure = Calc
Formula = [MeasureBand22]>0.1
DynamicVariables = 1
IfCondition = ([Block23_2]=1)
IfTrueAction = [!SetVariable Block23_2Color #Color#]
IfFalseAction = [!SetVariable Block23_2Color 0,0,0,0]

[Block23_3]
Measure = Calc
Formula = [MeasureBand22]>0.2
DynamicVariables = 1
IfCondition = ([Block23_3]=1)
IfTrueAction = [!SetVariable Block23_3Color #Color#]
IfFalseAction = [!SetVariable Block23_3Color 0,0,0,0]

[Block23_4]
Measure = Calc
Formula = [MeasureBand22]>0.3
DynamicVariables = 1
IfCondition = ([Block23_4]=1)
IfTrueAction = [!SetVariable Block23_4Color #Color#]
IfFalseAction = [!SetVariable Block23_4Color 0,0,0,0]

[Block23_5]
Measure = Calc
Formula = [MeasureBand22]>0.4
DynamicVariables = 1
IfCondition = ([Block23_5]=1)
IfTrueAction = [!SetVariable Block23_5Color #Color#]
IfFalseAction = [!SetVariable Block23_5Color 0,0,0,0]

[Block23_6]
Measure = Calc
Formula = [MeasureBand22]>0.5
DynamicVariables = 1
IfCondition = ([Block23_6]=1)
IfTrueAction = [!SetVariable Block23_6Color #Color#]
IfFalseAction = [!SetVariable Block23_6Color 0,0,0,0]

[Block23_7]
Measure = Calc
Formula = [MeasureBand22]>0.6
DynamicVariables = 1
IfCondition = ([Block23_7]=1)
IfTrueAction = [!SetVariable Block23_7Color #Color#]
IfFalseAction = [!SetVariable Block23_7Color 0,0,0,0]

[Block23_8]
Measure = Calc
Formula = [MeasureBand22]>0.7
DynamicVariables = 1
IfCondition = ([Block23_8]=1)
IfTrueAction = [!SetVariable Block23_8Color #Color#]
IfFalseAction = [!SetVariable Block23_8Color 0,0,0,0]

[Block23_9]
Measure = Calc
Formula = [MeasureBand22]>0.8
DynamicVariables = 1
IfCondition = ([Block23_9]=1)
IfTrueAction = [!SetVariable Block23_9Color #Color#]
IfFalseAction = [!SetVariable Block23_9Color 0,0,0,0]

[Block23_10]
Measure = Calc
Formula = [MeasureBand22]>0.9
DynamicVariables = 1
IfCondition = ([Block23_10]=1)
IfTrueAction = [!SetVariable Block23_10Color #Color#]
IfFalseAction = [!SetVariable Block23_10Color 0,0,0,0]

[Block24_1]
Measure = Calc
Formula = [MeasureBand23]>0.0
DynamicVariables = 1
IfCondition = ([Block24_1]=1)
IfTrueAction = [!SetVariable Block24_1Color #Color#]
IfFalseAction = [!SetVariable Block24_1Color 0,0,0,0]

[Block24_2]
Measure = Calc
Formula = [MeasureBand23]>0.1
DynamicVariables = 1
IfCondition = ([Block24_2]=1)
IfTrueAction = [!SetVariable Block24_2Color #Color#]
IfFalseAction = [!SetVariable Block24_2Color 0,0,0,0]

[Block24_3]
Measure = Calc
Formula = [MeasureBand23]>0.2
DynamicVariables = 1
IfCondition = ([Block24_3]=1)
IfTrueAction = [!SetVariable Block24_3Color #Color#]
IfFalseAction = [!SetVariable Block24_3Color 0,0,0,0]

[Block24_4]
Measure = Calc
Formula = [MeasureBand23]>0.3
DynamicVariables = 1
IfCondition = ([Block24_4]=1)
IfTrueAction = [!SetVariable Block24_4Color #Color#]
IfFalseAction = [!SetVariable Block24_4Color 0,0,0,0]

[Block24_5]
Measure = Calc
Formula = [MeasureBand23]>0.4
DynamicVariables = 1
IfCondition = ([Block24_5]=1)
IfTrueAction = [!SetVariable Block24_5Color #Color#]
IfFalseAction = [!SetVariable Block24_5Color 0,0,0,0]

[Block24_6]
Measure = Calc
Formula = [MeasureBand23]>0.5
DynamicVariables = 1
IfCondition = ([Block24_6]=1)
IfTrueAction = [!SetVariable Block24_6Color #Color#]
IfFalseAction = [!SetVariable Block24_6Color 0,0,0,0]

[Block24_7]
Measure = Calc
Formula = [MeasureBand23]>0.6
DynamicVariables = 1
IfCondition = ([Block24_7]=1)
IfTrueAction = [!SetVariable Block24_7Color #Color#]
IfFalseAction = [!SetVariable Block24_7Color 0,0,0,0]

[Block24_8]
Measure = Calc
Formula = [MeasureBand23]>0.7
DynamicVariables = 1
IfCondition = ([Block24_8]=1)
IfTrueAction = [!SetVariable Block24_8Color #Color#]
IfFalseAction = [!SetVariable Block24_8Color 0,0,0,0]

[Block24_9]
Measure = Calc
Formula = [MeasureBand23]>0.8
DynamicVariables = 1
IfCondition = ([Block24_9]=1)
IfTrueAction = [!SetVariable Block24_9Color #Color#]
IfFalseAction = [!SetVariable Block24_9Color 0,0,0,0]

[Block24_10]
Measure = Calc
Formula = [MeasureBand23]>0.9
DynamicVariables = 1
IfCondition = ([Block24_10]=1)
IfTrueAction = [!SetVariable Block24_10Color #Color#]
IfFalseAction = [!SetVariable Block24_10Color 0,0,0,0]

[Block25_1]
Measure = Calc
Formula = [MeasureBand24]>0.0
DynamicVariables = 1
IfCondition = ([Block25_1]=1)
IfTrueAction = [!SetVariable Block25_1Color #Color#]
IfFalseAction = [!SetVariable Block25_1Color 0,0,0,0]

[Block25_2]
Measure = Calc
Formula = [MeasureBand24]>0.1
DynamicVariables = 1
IfCondition = ([Block25_2]=1)
IfTrueAction = [!SetVariable Block25_2Color #Color#]
IfFalseAction = [!SetVariable Block25_2Color 0,0,0,0]

[Block25_3]
Measure = Calc
Formula = [MeasureBand24]>0.2
DynamicVariables = 1
IfCondition = ([Block25_3]=1)
IfTrueAction = [!SetVariable Block25_3Color #Color#]
IfFalseAction = [!SetVariable Block25_3Color 0,0,0,0]

[Block25_4]
Measure = Calc
Formula = [MeasureBand24]>0.3
DynamicVariables = 1
IfCondition = ([Block25_4]=1)
IfTrueAction = [!SetVariable Block25_4Color #Color#]
IfFalseAction = [!SetVariable Block25_4Color 0,0,0,0]

[Block25_5]
Measure = Calc
Formula = [MeasureBand24]>0.4
DynamicVariables = 1
IfCondition = ([Block25_5]=1)
IfTrueAction = [!SetVariable Block25_5Color #Color#]
IfFalseAction = [!SetVariable Block25_5Color 0,0,0,0]

[Block25_6]
Measure = Calc
Formula = [MeasureBand24]>0.5
DynamicVariables = 1
IfCondition = ([Block25_6]=1)
IfTrueAction = [!SetVariable Block25_6Color #Color#]
IfFalseAction = [!SetVariable Block25_6Color 0,0,0,0]

[Block25_7]
Measure = Calc
Formula = [MeasureBand24]>0.6
DynamicVariables = 1
IfCondition = ([Block25_7]=1)
IfTrueAction = [!SetVariable Block25_7Color #Color#]
IfFalseAction = [!SetVariable Block25_7Color 0,0,0,0]

[Block25_8]
Measure = Calc
Formula = [MeasureBand24]>0.7
DynamicVariables = 1
IfCondition = ([Block25_8]=1)
IfTrueAction = [!SetVariable Block25_8Color #Color#]
IfFalseAction = [!SetVariable Block25_8Color 0,0,0,0]

[Block25_9]
Measure = Calc
Formula = [MeasureBand24]>0.8
DynamicVariables = 1
IfCondition = ([Block25_9]=1)
IfTrueAction = [!SetVariable Block25_9Color #Color#]
IfFalseAction = [!SetVariable Block25_9Color 0,0,0,0]

[Block25_10]
Measure = Calc
Formula = [MeasureBand24]>0.9
DynamicVariables = 1
IfCondition = ([Block25_10]=1)
IfTrueAction = [!SetVariable Block25_10Color #Color#]
IfFalseAction = [!SetVariable Block25_10Color 0,0,0,0]